module.exports = {
    countries: [
        {name: 'هلند', id: 'nl'}, 
        {name: 'اتریش', id: 'at'}, 
        {name: 'آلمان', id: 'de'}, 
        {name: 'مجارستان', id: 'hu'}, 
        {name: 'کانادا', id: 'ca'}, 
        {name: 'ایتالیا', id: 'it'}, 
        {name: 'انگلستان', id: 'gb'}, 
        {name: 'اسپانیا', id: 'es'}, 
        {name: 'فرانسه', id: 'fr'}, 
        {name: 'آمریکا', id: 'us'}, 
        {name: 'ترکیه', id: 'tr'}, 
        {name: 'روسیه', id: 'ru'}, 
        {name: 'لهستان', id: 'pl'}, 
        {name: 'فنلاند', id: 'fi'}, 
        {name: 'سوئد', id: 'se'}, 
        {name: 'بلژیک', id: 'be'}, 
        {name: 'استرالیا', id: 'au'}, 
        {name: 'دانمارک', id: 'dk'}, 
        {name: 'بلغارستان', id: 'bg'}, 
        {name: 'چین', id: 'cn'}, 
        {name: 'کره جنوبی', id: 'kr'}, 
    ],
    workCountries: [
        {name: 'هلند', id: 'nl'}, 
        {name: 'اتریش', id: 'at'}, 
        {name: 'آلمان', id: 'de'}, 
        {name: 'مجارستان', id: 'hu'}, 
        {name: 'کانادا', id: 'ca'}, 
        {name: 'ایتالیا', id: 'it'}, 
        {name: 'انگلستان', id: 'gb'}, 
        {name: 'اسپانیا', id: 'es'}, 
        {name: 'فرانسه', id: 'fr'}, 
        {name: 'آمریکا', id: 'us'}, 
        {name: 'ترکیه', id: 'tr'}, 
        {name: 'روسیه', id: 'ru'}, 
        {name: 'لهستان', id: 'pl'}, 
        {name: 'فنلاند', id: 'fi'}, 
        {name: 'سوئد', id: 'se'}, 
        {name: 'بلژیک', id: 'be'}, 
        {name: 'استرالیا', id: 'au'}, 
        {name: 'دانمارک', id: 'dk'}, 
        {name: 'بلغارستان', id: 'bg'}, 
        {name: 'چین', id: 'cn'}, 
        {name: 'کره جنوبی', id: 'kr'}, 
    ]
}

